### ISSUE TITLE
consider conditionally installing 'apt-transport-https'

### ISSUE THREAD

**Issue by mburns** [mmi-cookbooks/ele-filebeat#2]
Do we want to force this install in all cases?

**Comment by drenalin23** [comment]
This package enables the usage of 'deb https://foo distro main' lines in the /etc/apt/sources.list so that all package managers using the libapt-pkg library can access metadata and packages available in sources accessible over https (Hypertext Transfer Protocol Secure).

This should already be on every Ubuntu box we run.  The reason we force install it in the cookbook is that the docker image for Ubuntu 14.04 on travisci doesn't have it...

**Comment by drenalin23** [comment]
https://packages.debian.org/sid/admin/apt-transport-https
